version: '3'

# docker-compose up -d

networks:
  traefik-net:
    external: true
  internal:
    external: false

services:
  docker-hoster:
    container_name: docker-hoster
    image: dvdarias/docker-hoster
    networks:
      - internal
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - /etc/hosts:/tmp/hosts

    
  reverse-proxy:
    container_name: traefik
    image: traefik # The official Traefik docker image
    command: --api --docker # Enables the web UI and tells Traefik to listen to docker
    restart: always
    #network_mode: bridge
    networks:
      - traefik-net
      - internal
    ports:
      - 80:80     # The HTTP port
      - 443:443
      - 127.0.0.1:8080:8080 # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
      - ./stackdata/traefik/traefik.toml:/traefik.toml # Traefik configuration file
      - ./stackdata/traefik/acme:/acme # Tell Traefik to save SSL certs here


  portainer:
    container_name: portainer
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    #network_mode: bridge
    networks:
      - traefik-net
    ports:
      - 127.0.0.1:9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./stackdata/portainer:/data
    labels:
      - "traefik.enable=false"

  strapi:
    container_name: api
    image: strapi/strapi
    restart: always
    depends_on:
      - mysql
    #network_mode: bridge
    networks:
      - traefik-net
      - internal
    ports:
      - 1337:1337
    links:
       - mysql
    volumes: 
      - ./stackdata/api:/usr/src/api/api-app
    environment:
      APP_NAME: api-app
      DATABASE_CLIENT: mysql
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: api_db
      DATABASE_USERNAME: api_user
      DATABASE_PASSWORD:
    labels:
      ###- "traefik.enable=true"
      - "traefik.backend=api"
      - "traefik.docker.network=traefik-net"
      - "traefik.frontend.rule=PathPrefixStrip:/api"
      - "traefik.port=1337"
    
  wordpress:
    image: wordpress:latest
    volumes:
      - ./stackdata/wordpress:/var/www/html
    ports:
      - 80
    labels:
      - "traefik.frontend.rule=${TRAEFIK_FRONTEND_RULE}"
      - "traefik.port=80"
      - "traefik.docker.network=traefik-net"
    links:
       - mysql
    networks:
      - internal
      - traefik-net
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_NAME: wp_db
      WORDPRESS_DB_PASSWORD:
      
  # export MYSQL_ROOT_PASSWORD=secure_database_password  
  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD:
    volumes:
      - ./stackdata/mysql:/var/lib/mysql
    restart: always
    #network_mode: bridge
    networks:
      - internal
    
    ports:
      - 127.0.0.1:3306:3306
    #networks:
    #  - internal
    depends_on:
      - docker-hoster
    labels:
      - traefik.enable=false

