version: '3'

# docker-compose up -d

networks:
  web:
    external: true
  internal:
    external: false

services:
  docker-hoster:
    container_name: docker-hoster
    image: dvdarias/docker-hoster
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - /etc/hosts:/tmp/hosts

    
  reverse-proxy:
    container_name: traefik
    image: traefik # The official Traefik docker image
    command: --api --docker # Enables the web UI and tells Traefik to listen to docker
    restart: always
    #network_mode: bridge
    networks:
      - web
      - internal
    ports:
      - 80:80     # The HTTP port
      - 127.0.0.1:8080:8080 # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events


  portainer:
    container_name: portainer
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    #network_mode: bridge
    networks:
      - web
    ports:
      - 127.0.0.1:9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      #- "traefik.frontend.rule=PathPrefixStrip:/portainer"
      #- "traefik.backend=portainer"
      #- "traefik.port=9000"
      #- "traefik.weight=10"
      - "traefik.enable=false"
      #- "traefik.passHostHeader=true"
      ##- "traefik.docker.network=ntw_front"
      #- "traefik.frontend.entryPoints=http"
      ##- "traefik.backend.loadbalancer.swarm=true"
      ##- "traefik.backend.loadbalancer.method=drr"
      ## https://github.com/containous/traefik/issues/563#issuecomment-421360934
      #- "traefik.frontend.redirect.regex=^(.*)/portainer$$"
      #- "traefik.frontend.redirect.replacement=$$1/portainer/"
      #- "traefik.frontend.rule=PathPrefix:/portainer;ReplacePathRegex: ^/portainer/(.*) /$$1"    

  
  strapi:
    container_name: strapi
    image: strapi/strapi
    restart: always
    depends_on:
      - mysql
    #network_mode: bridge
    networks:
      - web
      - internal

    ports:
      - 127.0.0.1:1337:1337
    links:
       - mysql
    volumes: 
      - ./strapi-app:/usr/src/api/strapi-app
    environment:
      APP_NAME: strapi-app
      DATABASE_CLIENT: mysql
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: api_db
      DATABASE_USERNAME: api_user
      DATABASE_PASSWORD:
    labels:
      - "traefik.enable=false"

    

      
  # export MYSQL_ROOT_PASSWORD=secure_database_password  
  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD:
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    #network_mode: bridge
    networks:
      - internal
    
    ports:
      - 127.0.0.1:3306:3306
    #networks:
    #  - internal
    depends_on:
      - docker-hoster
    labels:
      - traefik.enable=false


volumes:
  portainer_data:
  mysql_data:
